### ISSUE TITLE
in compute_es.r, what's the difference between corr and r?

### ISSUE THREAD

**Issue by mllewis** [langcog/metalab-archive#101]
@shotsuji @mikabr

**Comment by shotsuji** [comment]
@mllewis corr is the correlation between two within-subject measurement points (needed for calculation of d effect size variance). r is the correlation coefficient of two variables that would be used directly as an effect size.

**Comment by mllewis** [comment]
@shotsuji  That makes sense, but is inconsistent with the codebook at the template which calls the correlation between two continuous variables "corr".

**Comment by shotsuji** [comment]
@mllewis which codebook? i am looking at the field specifications on the MetaLab site where it is correct. do you want to change it where you;re seeing it? Or is it more complicated than that?
