### ISSUE TITLE
Within-two and within_one d_var_calc formula 

### ISSUE THREAD

**Issue by shotsuji** [langcog/metalab-archive#104]
@mikabr, I am just running through the d_var_calc formulae and I cannot reproduce why we wrote them the way we did - could you please have a look together with me?

For within_two, in compute_ES.R we do
((1 / n_1) + (d_calc ^ 2 / (2 \* n_1))) \* 2 \* (1 - corr)
However, in InPhonDB/textbooks what is used is
(2 \* (1 - corr)/ n_1) + (d_calc ^ 2 / (2 \* n_1))
I can't remember having changed the formula that way - can you?

For within_one, in compute_ES.R we do
(2/n_1) + (d_calc ^ 2 / (4 \* n_1))
which is essentially the formula for between assuming equal sample sizes for both groups.
For the within_one case there is not really any textbook solution- in InPhon DB I used the within_two formula assuming cor = 0 - but I am just wondering whether you remember why we decided this way.

**Comment by mikabr** [comment]
I don't recall anything about reasons to change the formula – maybe we made a mistake? The difference seems to just be in the order/parenthesizing of the terms.

For `within_one` we did `between` with equal sample sizes, yeah. No idea if that or `within_two` with `corr=0` is better.

**Comment by shotsuji** [comment]
@mikabr ok good to know about within_two! I'll look into it one more time and will change it to the textbook version if no new evidence pops up.
And I'll try to inquire about the ideal solution for within_one.
Thank you!

**Comment by shotsuji** [comment]
Hi @mllewis 
I have changed the formula of d_var_calc for within_two as described above in this issue. It was a bracketing error.
I will not close this thread yet since I still need to figure out whether anyone has any real recommendations on how to calculate variance for within_one the best way (the q we got at cogsci). But at least the way we do it now is one of the possible solutions and should not be incorrect. So should be fine for submission, and if we figure out sth better until resubmit values might slightly change.

**Comment by mcfrank** [comment]
Thanks, Sho!

Mike

**Comment by shotsuji** [comment]
Short version: Within_two change should have been implemented long ago; it doesn't lead to any big changes in resulting variances so I do not think papers need to be changed. Within_one change is one we've been pondering for a while and I finally got to it. This one leads to somewhat bigger changes (see attached figure).
I won't push anything up for the moment - if I don't here otherwise, I will document these changes in the script and push them up in about a week.

Disclaimer: This is a separate issue from the one that Molly opened about within-effect sizes based on Jake Westfall - that one I answered to in another message and also updated the github answer.

Long version

    Within_two
    From: d_var_calc<- ((1 / n_1) + (d_calc ^ 2 / (2 * n_1))) * 2 * (1 - corr)
    To: d_var_calc <- (2 * (1 - corr)/ n_1) + (d_calc ^ 2 / (2 * n_1))
    Reason: The new formula is the one used in textbooks - we noticed this discrepancy at Cogsci and I had thought I had changed it in September, but I had committed without syncing - sorry for that. This change does not cause big deviations in ES calculations.

    Within_one
    From: d_var_calc <- (2/n_1) + (d_calc ^ 2 / (4 * n_1))
    To: d_var_calc <- (1 / n_1) + (d_calc ^ 2 / (2 * n_1))
    Reason: There is no good documentation for how to deal with within_one. We had so far used the formula for between-designs, which was not ideal. Paired t-tests (where the difference score is compared against baseline) are the same as one-sample t-tests. Thus, the formula for within_two is more appropriate. I had backed down from that because I couldn't quite find out how to set the correlation term. With the help of Wolfgang Viechtbauer (the creator of metafor), I finally figured it out. We should "set" the correlation to r=0.5 to make it the above formula; basically just taking out the correlation term. He noted that he'd use the same logic as for the variance of the effect sizes, which is, for within_two (with equal variance at two testing points) variance = 2 * (1 - corr) * d_calc^2 / n, but should be variance = d_calc^2/n for within_one.

**Comment by shotsuji** [comment]
I changed the formulae as described above
