### ISSUE TITLE
When updating R to latest version: Fatal error when running global.R

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab-archive#112]
Under Windows 10 and iOS, when running _global.R_ RStudio (latest version, same for R and all packages) encounters a fatal error and the session aborts. The error message from _global.R_ is "This Feather file is old and will not be readable beyond the 0.3.0 release" (Windows 10)

This Feather file is old and will not be readable beyond the 0.3.0 release
Error in coldataFeather(x, i) : 
  embedded nul in string: 'SNFNSNmultiple-talkersmultiple-talkerssingle-talkersingle-talkeronsetcodaonsetcodacodapost-hoc-youngerpost-hoc-olderFNSNpartially-conflictingnon-conflictingFEA1\0\0\0\017\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\004\0\0\0\b\0\0\0\v\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\0\016\0\0\011mo11mo4mo4moFEA1\0\0\0\0\f\0\0\0\030\0\0\0$\0\0\00\0\0\0<\0\0\0H\0\0\0T\0\0\0`\0\0\0l\0\0\0x\0\0\0\x84\0\0\0\x90\0\0\0\x9c\0\0\0\xa8\0\0\0\xb4\0\0\0\xc0\0\0\0\xcc\0\0\0\xd8\0\0\0\xe4\0\0\0\xf0\0\0\0\xfc\0\0\0\b\001\0\0\024\001\0\0 \001\0\0,\001\0\08\001\0\0D\001\0\0P\001\0\0\\001\0\0h\001\0\0t\001\0\0\x80\001\0\0\x8c\001\0\0\x98\001\0\0\xa4\001\0\0\xb0\001\0\0
(iOS)

**Comment by christinabergmann** [comment]
Note on the update: I thought this was a Windows issue until I updated R on my mac, too.

**Comment by mcfrank** [comment]
This is a terrible cluster. I updated server feather to 0.3.0 and awful things are happening in some of the feather files such that that we segfault when loading and the site is now down. The problem is that A) we can't compile the old feather any more, so packrat on this is useless, and B) we can't easily roll back to CSV because there are null characters in the files. I would love to get some help on this - @mikabr any thoughts?

**Comment by tjmahr** [comment]
I couldn't use the site today, found this issue, forked the repository, restored packrat snapshot, and ran the Shiny app locally, and everything worked fine. So I guess the site needs to be redeployed?

**Comment by mcfrank** [comment]
Thanks TJ - we are struggling with a bug that shows up only on our
production machine and not locally - I'm working locally too but get a "c
stack" out of memory error dumped from the server. I'm pretty sure it's
being cause by metafor::rma but I don't know why. I can even run the same
rma models on the server outside of shiny.
