### ISSUE TITLE
Metlab site not displaying properly

### ISSUE THREAD

**Issue by kristabh** [langcog/metalab-archive#124]
Meta-analytic visualizations not working on Chrome or Safari (OSX) --> Not able to select a domain/effect.

![Screen Shot 2019-05-27 at 2 26 58 PM](https://user-images.githubusercontent.com/7000200/58434820-96c7d980-808b-11e9-96c5-899c9bfe8f7b.png)

**Comment by mcfrank** [comment]
sorry about that! we are having some issues. should be working now.
