### ISSUE TITLE
Add live counts of database statistics

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab-archive#23]
Add a counter of _independent_ ES, N children (only from those ES), N papers.

**Comment by mikabr** [comment]
How app is calculating these values:
Number of effect sizes: number of rows in data
Number of papers: number of unique values of unique_ID in the data
Number of subjects: sum of all n_1 values and n_2 values
Does that sounds right?

**Comment by christinabergmann** [comment]
Sounds right, iff NA effect sizes were removed beforehand (and ideally also same infant groups were collapsed into one).

**Comment by mikabr** [comment]
I was removing NA effect sizes beforehand, but stopped because the numbers quoted in the doc seemed much closer to what you get that way. I can re-remove them. Not sure what you mean by same infant groups?

**Comment by christinabergmann** [comment]
The column same_infant codes whether the same group of participants contributed data to more than one condition, then they shouldn't be counted twice. ID for infant groups is in column study_num for InPhonDB.

**Comment by mikabr** [comment]
Digging into this is making me increasingly confused -- I thought that the combination of unique_ID, study_num, condition, dependent_measure (and possibly same_infant?) should uniquely identify a row, but that appears not to be true at all. What does it mean when two rows have the same value for all of those, but different effect sizes?

**Comment by christinabergmann** [comment]
So, I checked myself, and what can happen are two things: (1) Across separately analyzed infant groups, only one age measure is reported. Keep all data. Should be identified by same_infant == "no" or 0. OR: (2) The same infant group is tested in multiple conditions (for example in Kuhl1979 in 5 test blocks with different stimuli). Then different ES, based on different x could be derived. In this case, we took the median of all numeric rows for InWordDB. 
In any case, it is crucial for the DB to reliable track where the same infants were really tested.

**Comment by mcfrank** [comment]
What's the status of this issue? Can we close it?

**Comment by mikabr** [comment]
While the numbers exist, I'm not completely sure they are right, especially the participant count. So the status is that we should double check that the data satisfy the properties we want them to in terms of which fields uniquely identify what, and double check that the summary counts are right given that.

**Comment by christinabergmann** [comment]
How exactly do you compute the number of participants? It should be the sum of all _n_1+n_1_ for all different entries of _same_infant_ within one _unique_id_ (does that make sense?). 
Assuming we all tracked repeated measures correctly, this should now be the right count.
