### ISSUE TITLE
specification for description of meta-analyses

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab-archive#25]
This issue is a description of what the markdown spec should look like for included MAs:
- phenomenon name
- citation if published
- description of phenomenon
- details of literature search procedure
- details of coding procedure 
  - including sign decisions (e.g., novelty preference, familiarity preference, etc.)
- external reference point for the study

**Comment by mikabr** [comment]
This isn't an issue, so I copied its contents into a [wiki page](https://github.com/langcog/metalab/wiki/Specification-for-description-of-meta-analyses)
