### ISSUE TITLE
who are we? 

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab-archive#37]
mugshots, contact info, key interests?

**Comment by mikabr** [comment]
This is now in a tab under documentation. Feel free to change your picture (in `dashboard/www/images/people/`) and edit any of your information (in `metadata/people.yaml`).

**Comment by mcfrank** [comment]
Could we make this a separate "about" subheading? doesn't feel to me like
it goes next to the yaml specification but instead up a level in terms of
hierarchy.

Mike

**Comment by mikabr** [comment]
It feels like then the "overview" and "about" panes would both be pretty sparse, how do you feel about combining them into one?

**Comment by mcfrank** [comment]
yes, sounds great!

Mike
