### ISSUE TITLE
check correctness of d_var_calc formula

### ISSUE THREAD

**Issue by mikabr** [langcog/metalab-archive#43]

**Comment by mikabr** [comment]
We are currently using
`((n_1 + n_2) / (n_1 * n_2)) + (d_calc ^ 2 / (2 * (n_1 + n_2)))`

[stackoverflow](http://stats.stackexchange.com/questions/8487/how-do-you-calculate-confidence-intervals-for-cohens-d) says
`(((n_1 + n_2) / (n_1 * n_2)) + (d_calc ^ 2 / (2 * (n_1 + n_2 - 2)))) * ((n_1 + n_2) / (n_1 + n_2 - 2))`

anyone know what the right formula is?

**Comment by shotsuji** [comment]
The formula we are using is for the SE, stackoverflow is for variance.
Either can be used for MA - but you're right our name is misleading. Do we want to rename it to d_se?

**Comment by mcfrank** [comment]
Hey Sho, are you sure? Looks like the second formula here is the same as the one we are using, except that it has some DF corrections in it: e.g., that last 

`(n_1 + n_2) / (n_1 + n_2 - 2)`

seems like it just corrects by some factor slightly > 1, especially for small N. But I don't think one is SE and one is variance, right?

**Comment by shotsuji** [comment]
Hi,
Of course, sorry, my bad. Both are variances of course.
FYI Christina and I just checked in two MA handbooks (Lipsey & Willson and Borenstein) as well as in R's compute.es package. All of them use the version we have been using.

**Comment by mcfrank** [comment]
That's comforting! OK, good case for inaction. ;)

Mike
