### ISSUE TITLE
#ES based on r -  convert to Fisher's z?

### ISSUE THREAD

**Issue by shotsuji** [langcog/metalab-archive#50]
Correlation coefficient MA experts - I just read that it is recommended to convert r to Fisher;s z scale and do analyses based on that, since the variance depends strongly on the correlation (I got it from a textbook but there's some discussion on that [here](http://stats.stackexchange.com/questions/26485/does-transformation-of-r-into-fisher-z-benefit-a-meta-analysis).
In that case, we would do z = 0.5 x ln((1+r)/(1-r)), and variance of z = 1/(n-3)
Any opinions?

**Comment by mcfrank** [comment]
default: @mikabr will just add this as a pulldown.
