### ISSUE TITLE
add more text to team page?

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab-archive#57]

**Comment by mcfrank** [comment]
examples: 

Sho Tsuji
Sho has co-developed the concept of community-augmented meta-analyses (Tsuji, Bergmann, & Cristia, 2014), pushing the idea of open-access, dynamic, and collaborative meta-analyses. In metalab, she has been working on formulas for calculating effect sizes in metalab.  Data-wise, she has contributed meta-analyses on native and non-native vowel discrimination to metalab. She is happy to answer questions on effect sizes and on how to set up a meta-analysis.

Sho is the main contact person for these databases: Vowel Discrimination (InPhonDB).

Christina Bergmann
Community-augmented meta-analyses (CAMAs), which means sharing data so others can re-use and extend our meta-analyses, were developed jointly by Sho, Christina, and Alex (Tsuji, Bergmann, & Cristia, 2014). Christina is particularly interested in the educational and community side of this idea, which has been picked up by metalab.  
Christina has worked on measures of publication biases, for example p-curves [link to report], to check that the data we collect is sound. She is happy to discuss this topic, word segmentation and possibilities to extend this database, and will probably try to convince you to join this team effort.

**Comment by mcfrank** [comment]
Pro: Gives more background on people and their contributions. Cons: hard to lay out, need to generate consistent text for everyone and keep it up to date.

**Comment by christinabergmann** [comment]
How about a link to personal home pages instead?

**Comment by mcfrank** [comment]
Certainly fine by me!
