### ISSUE TITLE
Add curator to datasets

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab-archive#60]
Add dataset curator, so they show up eg on the documentation overview page.

I list the current curators as far as I can identify them below (note also some dataset name change suggestions).

Vowel discrimination (native/non-native) 
_Sho Tsuji_

Word segmentation
_Christina Bergmann_

Infant directed speech preference
_Alex Cristia_

Mutual exclusivity
_Molly Lewis_

Label advantage in concept learning 
_Molly Lewis_

Gaze following 
_Mike Frank?_

Online word recognition 
_Mike Frank?_

Phonotactic learning 
_Alex Cristia_

[Statistical?] Sound [category??] learning 
_Alex Cristia_

**Comment by mcfrank** [comment]
good idea - maybe this can get wrapped into a more general addition to the dataset descriptions, which includes a short description (for the main page) and more info (for the documentation)

**Comment by christinabergmann** [comment]
Sorry, but I don't see a curator in the documentation tab, would be very useful to list one contact person for each MA, for example when soliciting contributions of unpublished data this is crucial. Or should we just say mail to metalab@googlegroups.com?
