### ISSUE TITLE
Change funnel plot label from unique_ID to short_cite

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab-archive#66]
unique_ID is not very consistent and also not informative for some MAs, so I suggest we move to using short_cite. This is also more readable.

**Comment by mikabr** [comment]
some of the `short_cite` entries are rather long, so the forest plot is way too squished (e.g. look at gaze following)

**Comment by mikabr** [comment]
also there seem to be encoding issues in `short_cite` (e.g. in vowel discrimination)

**Comment by mcfrank** [comment]
Christina, are you reopening because it doesn't look fixed? It won't be
live on the website until tomorrow (because the site hasn't updated).

Mika, I cut down papers with > 6 authors to et al. in the short cite. We
could do that for more than 3 authors, I'd be fine with that. Gaze
following looks OKish on my screen, but it is a bit cramped I guess.

Mike

**Comment by mcfrank** [comment]
Can you say more about what you mean by encoding issues? Oh, do you mean
the special characters in nuria sebastian galles' name?

Mike

**Comment by mikabr** [comment]
On my screen a lot of them look cramped, gaze following looks completely unreadable =\ Cutting down the number of displayed authors sounds like a good idea, maybe also making the text smaller?

**Comment by mcfrank** [comment]
OK, I don't have a programmatic way of cutting down short_cite, do you have
a thought? I just did it by hand for the few > 6 author paper.

Mike

**Comment by christinabergmann** [comment]
How about a character limit? It's quite easy to just check in the google sheets version. I'm happy to shorten them and started with InWordDB already. I somewhat arbitrarily chose 35 characters, does that work? 

(I didn't reopen, btw, I guess it was Mika because of the ugliness issue, which I completely understand).

**Comment by mcfrank** [comment]
Ah... yes, you're right, it was Mika sorry.

I think it'd be preferable to have an et al. convention so they are not
ugly. You are thinking do "et al." when it's more than 35 chars?

best,

Mike

On Thu, Apr 7, 2016 at 1:43 AM, Christina Bergmann <notifications@github.com

**Comment by christinabergmann** [comment]
Exactly that, I already changed to et al. in InWordDB when there were more than 35 chars. Imo that looks ok, but less characters are also possible.

**Comment by mcfrank** [comment]
OK, that sounds great.

Mike

On Thu, Apr 7, 2016 at 8:56 AM, Christina Bergmann <notifications@github.com

**Comment by christinabergmann** [comment]
Done, if there's nothing else going wrong, we can close, non? 
NB: I removed some special chars that I spotted on the way. Hope it's all fine and dandy now.

**Comment by mcfrank** [comment]
Thanks!

Mike

On Thu, Apr 7, 2016 at 9:25 AM, Christina Bergmann <notifications@github.com
