### ISSUE TITLE
SoundSymbolismMA added

### ISSUE THREAD

**Issue by shotsuji** [langcog/metalab-archive#68]
Hi,
I added soundsymbolism to the tabular data folder. I only need to add one full reference then it's complete. Didn't incorporate it at other locations so far.
Sho

**Comment by mllewis** [comment]
Excellent! That's exciting.

Molly

**Comment by shotsuji** [comment]
Thanks! Still not fully resolved the issue of how to actually analyze them though, i'll keep you guys posted.

**Comment by mcfrank** [comment]
@shotsuji should we import this into the visualizations, or wait on you?

**Comment by shotsuji** [comment]
hi, it is complete, you can import - sorry for being late, in the midst of moving and visa trouble!
