### ISSUE TITLE
add absolute effect size option

### ISSUE THREAD

**Issue by mllewis** [langcog/metalab-archive#73]
For paradigms with familiarity/novelty preference (e.g., label advantage).

**Comment by mikabr** [comment]
do we want that option to be displayed for all datasets, or just for some specific ones (like label advantage)?

**Comment by mcfrank** [comment]
Hmm... that's actually a tricky question. @mllewis, what do you think? It
can be deceptive to flip ESs when there are just noisy datasets, but on the
other hand it doesn't make sense to interpret negative ES in the mean
estimate except as a familiarity preference.

I think I vote for not implementing this feature on the balance?

Mike
