### ISSUE TITLE
global.R crashes when creating "subjects"

### ISSUE THREAD

**Issue by pagepiccinini** [langcog/metalab-archive#97]
The code

subjects <- all_data %>%
  rowwise() %>%
  mutate(n_total = sum(c(n_1, n_2), na.rm = TRUE)) %>%
  distinct(dataset, study_ID, same_infant) %>%
  group_by(dataset) %>%
  summarise(num_subjects = sum(n_total))

crashes because the column "n_total" is removed by distinct(). Thus producing the error message(s):
Error: object 'n_total' not found
In addition: Warning message:
Grouping rowwise data frame strips rowwise nature

**Comment by pagepiccinini** [comment]
This is a result of the dplyr update, which is probably why it crashed on my computer but is running fine elsewhere. From https://blog.rstudio.org/2016/06/27/dplyr-0-5-0/:

If you give distinct() a list of variables, it now only keeps those variables (instead of, as previously, keeping the first value from the other variables). To preserve the previous behaviour, use .keep_all = TRUE:

Can I added in the fix?

**Comment by mcfrank** [comment]
If you add the fix we also need to update the packrat dplyr version... Are
you opening the code via the r project file? Packrat is supposed to protect
against this sort of bug.

**Comment by pagepiccinini** [comment]
Yeah it works fine within the project. The issue came up because I was sourcing the script from another project to do some side analyses. I can always just keep the different version locally and not push the change.

**Comment by mcfrank** [comment]
If you want to update in project go ahead but be sure to update the package
in packrat too!

**Comment by pagepiccinini** [comment]
Okay. Before I do that though, are there any other things that could go wrong with the dplyr update? I haven't read through the post in full yet about all of the changes.

**Comment by mcfrank** [comment]
Why don't you hold off then. There is plenty that could go wrong and you
would need test locally...

**Comment by pagepiccinini** [comment]
Agreed. Okay closing this then.
